export const SET_USER_NAME_REG = 'SET_USER_NAME_REG';
export const SET_USER_SURNAME_REG = 'SET_USER_SURNAME_REG';
export const SET_USER_PASSWORD_REG = 'SET_USER_PASSWORD_REG';
export const SET_USER_EMAIL_REG = 'SET_USER_EMAIL_REG';